/**
 * The behaviour vocabulary: what a node may ask the client script to do.
 *
 * Interactivity on a published site is declarative. A node opts in with
 * `data-bz-behavior`, marks its moving pieces with `data-bz-part`, and passes
 * settings as JSON in `data-bz-behavior-options`. The implementations live in
 * `client/widgets.js` and are written once; nothing here is a class name, so
 * restyling can never break the wiring.
 *
 * This list lives in a leaf module rather than in `index.mjs` because the layout
 * nodes need it and `index.mjs` imports them — five consumers now share it: the
 * layout schemas, the validator, the AI contract, the style panel, and the
 * schema export the backend validates against.
 */

export const BEHAVIOURS = [
  'carousel',
  'filter',
  'dropdown',
  'drawer',
  'rotator',
  'scrollstate',
  'dependentselect',
  'mapsync',
];

/**
 * Which parts each behaviour looks for, and what it does with them.
 *
 * Stated as data because an author — a person in the inspector or a model writing
 * markup — cannot guess these, and a mismarked part fails silently: the script
 * finds nothing and simply does not enhance. Offering the right names for the
 * chosen behaviour turns that class of dead end into a picker.
 *
 * `optional: false` means the behaviour does nothing at all without it.
 */
export const BEHAVIOUR_PARTS = {
  carousel: {
    track: { label: 'Rail', hint: 'The scrolling strip. Defaults to the node itself.', optional: true },
    slide: { label: 'Slide', hint: 'Each item. Must be a direct child of the rail.', optional: false, many: true },
    prev: { label: 'Previous button', optional: true },
    next: { label: 'Next button', optional: true },
    dots: { label: 'Dots container', hint: 'Leave it empty — one dot per slide is generated.', optional: true },
  },
  rotator: {
    slide: { label: 'Slide', optional: false, many: true },
    live: { label: 'Live region', hint: 'Where changes are announced. Defaults to the node.', optional: true },
    prev: { label: 'Previous button', optional: true },
    next: { label: 'Next button', optional: true },
    dots: { label: 'Dots container', optional: true },
  },
  filter: {
    control: { label: 'Filter control', hint: 'A button or input carrying the value to match.', optional: false, many: true },
    item: { label: 'Filterable item', optional: false, many: true },
    count: { label: 'Result count', optional: true },
    empty: { label: '"No results" message', optional: true },
  },
  dropdown: {
    trigger: { label: 'Trigger', optional: false, many: true },
    panel: { label: 'Panel', optional: false, many: true },
  },
  drawer: {
    toggle: { label: 'Toggle button', optional: false },
    panel: { label: 'Panel', optional: false },
    close: { label: 'Close button', optional: true, many: true },
  },
  scrollstate: {
    totop: { label: 'Back-to-top button', optional: true, many: true },
  },
  dependentselect: {
    parent: { label: 'Parent select', optional: false, many: true },
    child: { label: 'Dependent select', optional: false, many: true },
  },
  mapsync: {
    frame: { label: 'Map iframe', hint: 'Defaults to the first iframe inside.', optional: true },
  },
};

/** Every part name any behaviour recognises. */
export const PARTS = [
  ...new Set(Object.values(BEHAVIOUR_PARTS).flatMap(parts => Object.keys(parts))),
  // Generated by the carousel and rotator inside their dots container, and listed
  // so hand-authored dots validate too.
  'dot',
].sort();

/** The options each behaviour reads, for the inspector and the AI contract. */
export const BEHAVIOUR_OPTIONS = {
  carousel: { label: 'Accessible name for the rail.', perMove: 'Slides advanced per arrow press.' },
  rotator: { autoplay: 'Milliseconds between slides. Omit to require a click.' },
  filter: { match: 'How a control value is compared: "exact" or "includes".' },
  dropdown: { trigger: '"hover" or "click".', closeOnOutside: 'Close when clicking elsewhere.' },
  drawer: { lockScroll: 'Freeze the page behind the panel.' },
  scrollstate: { after: 'Pixels scrolled before the state turns on.', until: 'Selector to stop at.' },
  dependentselect: { source: 'Name of the option map published on window.' },
  mapsync: { message: 'Template for the address sent to the map.' },
};

/**
 * The attributes that wire a node to its behaviour.
 *
 * Shared by every layout node and by the widget wrapper so the contract is
 * identical wherever it is applied, and so a malformed options blob degrades to
 * "no options" rather than breaking the attribute it sits in.
 */
export function behaviourAttrs(props, ctx, nodeId) {
  const out = {};
  const behaviour = typeof props.behaviour === 'string' ? props.behaviour.trim() : '';
  const part = typeof props.part === 'string' ? props.part.trim() : '';

  if (behaviour && BEHAVIOURS.includes(behaviour)) out['data-bz-behavior'] = behaviour;
  else if (behaviour && ctx?.warn) ctx.warn(`Unknown behaviour "${behaviour}" (${nodeId || '?'}) — ignored.`);

  // A node may play several roles at once — "item control" is a drilldown's
  // middle column, filtered by the level above it and filtering the level below.
  // Each name is checked separately so one typo does not silently drop the rest.
  if (part) {
    const names = part.split(/\s+/).filter(Boolean);
    const known = names.filter(name => PARTS.includes(name));
    for (const name of names) {
      if (!PARTS.includes(name) && ctx?.warn) {
        ctx.warn(`Unknown behaviour part "${name}" (${nodeId || '?'}) — ignored.`);
      }
    }
    if (known.length) out['data-bz-part'] = known.join(' ');
  }

  const raw = props.behaviourOptions;
  if (out['data-bz-behavior'] && typeof raw === 'string' && raw.trim()) {
    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        out['data-bz-behavior-options'] = JSON.stringify(parsed);
      } else if (ctx?.warn) {
        ctx.warn(`Behaviour options on "${nodeId || '?'}" must be a JSON object — ignored.`);
      }
    } catch {
      if (ctx?.warn) ctx.warn(`Behaviour options on "${nodeId || '?'}" are not valid JSON — ignored.`);
    }
  }
  return out;
}
